import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    id("org.springframework.boot") version "2.2.0.RELEASE" apply false
    id("io.spring.dependency-management") version "1.0.8.RELEASE" apply false

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    kotlin("jvm") version "1.4.30"
    kotlin("plugin.spring") version "1.3.50" apply false
    kotlin("kapt") version "1.4.10"
    // Apply the application plugin to add support for building a CLI application.
    application

***REMOVED***

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
***REMOVED***

subprojects {
    repositories {
        mavenCentral()
        jcenter()
  ***REMOVED***

    apply {
        plugin("io.spring.dependency-management")

  ***REMOVED***
***REMOVED***

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation(project(":login"))
    implementation(project(":spotify"))
    implementation(project(":application"))

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
***REMOVED***

application {
    // Define the main class for the application.
    mainClassName = "AppKt"
***REMOVED***

tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = "1.8"
  ***REMOVED***
***REMOVED***

tasks.test {
    useJUnit()
    useJUnitPlatform()
***REMOVED***

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "AppKt"
  ***REMOVED***
***REMOVED***