/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    kotlin("jvm")
***REMOVED***

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
***REMOVED***

dependencies {
    //spring framework
    implementation("org.springframework.boot:spring-boot:2.4.0")
    implementation("org.springframework.boot:spring-boot-autoconfigure:2.4.0")
    implementation("org.springframework.boot:spring-boot-starter-web:2.4.0")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.4.0")
    implementation("org.springframework.boot:spring-boot-starter-validation:2.4.0")

    //mysql and database
    implementation("mysql:mysql-connector-java:8.0.23")

    implementation(kotlin("reflect"))

    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.12.1")
***REMOVED***
