/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")

    // Apply the application plugin to add support for building a CLI application.
    application
***REMOVED***

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
***REMOVED***

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation("org.jetbrains.kotlinx:kotlinx-serialization-runtime:1.0-M1-1.4.0-rc")

    //spring framework
    implementation("org.springframework.boot:spring-boot:2.4.0")
    implementation("org.springframework.boot:spring-boot-autoconfigure:2.4.0")
    implementation("org.springframework.boot:spring-boot-starter-web:2.4.0")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.4.0")
    implementation("org.springframework.boot:spring-boot-starter-validation:2.4.0")

    //mysql and database
    implementation("mysql:mysql-connector-java:8.0.23")
    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
***REMOVED***

application {
    // Define the main class for the application.
    mainClassName = "login.AppKt"
***REMOVED***
