/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    kotlin("jvm")
    kotlin("kapt")
    kotlin("plugin.spring")
    id("io.spring.dependency-management")

    // Apply the application plugin to add support for building a CLI application.
    application
***REMOVED***

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
***REMOVED***

dependencies {
    val retrofitVersion = "2.9.0"
    val moshiVersion = "1.11.0"

    //retrofit and moshi
    implementation("com.squareup.retrofit2:retrofit:$retrofitVersion")
    implementation("com.squareup.retrofit2:converter-moshi:$retrofitVersion")
    implementation("com.squareup.moshi:moshi-kotlin:$moshiVersion")
    implementation("com.squareup.moshi:moshi:$moshiVersion")

    kapt("com.squareup.moshi:moshi-kotlin-codegen:$moshiVersion")

    //mysql and database
    implementation("mysql:mysql-connector-java:8.0.23")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.4.0")
    implementation("org.springframework.boot:spring-boot-starter-validation:2.4.0")


    implementation(kotlin("reflect"))

    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.12.1")

***REMOVED***

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        jvmTarget = "1.8"
  ***REMOVED***
***REMOVED***

application {
    // Define the main class for the application.
    mainClassName = "spotify.AppKt"
***REMOVED***
